modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
    modId="kottle"
    version="1.3.0"
    type="LANGPROVIDER"

[[dependencies.kottle]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
